services:
  client:
    container_name: client
    build: 
      context: ./client
      dockerfile: Dockerfile
      target: development

    ports:
      - 8501:8501
    networks:
      app_net:
        ipv4_address: 172.30.0.2
    tty: true
    volumes:
      - ./client/app:/app
    environment:
      - SERVER_BASE_URL=http://server:8000

  server:
    container_name: server
    build: 
      context: ./server
      dockerfile: Dockerfile
      target: development
    ports:
      - 8000:8000
    networks:
      app_net:
        ipv4_address: 172.30.0.3
    tty: true
    volumes:
      - ./server/app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/config/api-key.json
      - DETECTRON2_CONFIG=/app/config/config.yaml
      - DETECTRON2_MODEL_WEIGHT=/app/config/model.pth
      - DETECTRON2_LABELS=/app/config/labels.json
      - OPENAI_APIKEY=/app/config/openai_key.txt
    
networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.30.0.0/24