services:
  web:
    container_name: web
    build: ./web
    ports:
      - 8501:8501
    tty: true
    volumes:
      - ./web:/app

  api:
    container_name: api
    build: ./api
    ports:
      - 8000:8000
    tty: true
    volumes:
      - ./api:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload