services:
  client:
    container_name: client
    build: ./client
    ports:
      - 8501:8501
    networks:
      app_net:
        ipv4_address: 172.30.0.2
    tty: true
    volumes:
      - ./client/app:/app

  server:
    container_name: server
    build: ./server
    ports:
      - 8000:8000
    networks:
      app_net:
        ipv4_address: 172.30.0.3
    tty: true
    volumes:
      - ./server/app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/config/api-key.json

networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.30.0.0/24