import os
DETECTRON2_CONFIG_PATH = os.environ["DETECTRON2_CONFIG"]
DETECTRON2_MODEL_WEIGHT_PATH = os.environ["DETECTRON2_MODEL_WEIGHT"]
DETECTRON2_LABELS_PATH = os.environ["DETECTRON2_LABELS"]
OPENAI_APIKEY_PATH = os.environ["OPENAI_APIKEY"]